# SPDX-License-Identifier: GPL-3.0-or-later
"""Tests for vault cryptography operations."""

import base64
import os

import pytest

from freeipa_mcp.vault_crypto import (
    VaultCryptoError,
    derive_symmetric_key,
    fernet_decrypt,
    fernet_encrypt,
    generate_random_bytes,
    generate_vault_session_key,
    unwrap_vault_data,
    wrap_vault_data,
)


class TestPBKDF2:
    """Test PBKDF2 key derivation."""

    def test_derive_key_deterministic(self):
        """Same password and salt produce same key."""
        key1 = derive_symmetric_key(b"password123", b"saltsalt")
        key2 = derive_symmetric_key(b"password123", b"saltsalt")
        assert key1 == key2

    def test_derive_key_length(self):
        """Derived key is 32 bytes."""
        key = derive_symmetric_key(b"password", b"salt")
        assert len(key) == 32

    def test_derive_key_salt_sensitive(self):
        """Different salts produce different keys."""
        key1 = derive_symmetric_key(b"password", b"salt1")
        key2 = derive_symmetric_key(b"password", b"salt2")
        assert key1 != key2

    def test_derive_key_password_sensitive(self):
        """Different passwords produce different keys."""
        key1 = derive_symmetric_key(b"password1", b"salt")
        key2 = derive_symmetric_key(b"password2", b"salt")
        assert key1 != key2


class TestFernet:
    """Test Fernet encryption/decryption."""

    def test_fernet_roundtrip(self):
        """Encrypt and decrypt recovers original data."""
        key = derive_symmetric_key(b"testpass", b"testsalt")
        plaintext = b"secret vault data"
        token = fernet_encrypt(plaintext, key)
        recovered = fernet_decrypt(token, key)
        assert recovered == plaintext

    def test_fernet_token_is_base64(self):
        """Fernet token is valid base64."""
        key = derive_symmetric_key(b"pass", b"salt")
        token = fernet_encrypt(b"data", key)
        # Should be decodable
        decoded = base64.urlsafe_b64decode(token)
        assert len(decoded) > 0

    def test_fernet_wrong_key_fails(self):
        """Decryption with wrong key fails."""
        key1 = derive_symmetric_key(b"key1", b"salt")
        key2 = derive_symmetric_key(b"key2", b"salt")
        token = fernet_encrypt(b"secret", key1)
        with pytest.raises(VaultCryptoError):
            fernet_decrypt(token, key2)

    def test_fernet_invalid_key_length(self):
        """Fernet rejects keys that aren't 32 bytes."""
        with pytest.raises(VaultCryptoError, match="32 bytes"):
            fernet_encrypt(b"data", b"shortkey")

    def test_fernet_invalid_token(self):
        """Fernet rejects invalid tokens."""
        key = derive_symmetric_key(b"pass", b"salt")
        with pytest.raises(VaultCryptoError):
            fernet_decrypt(b"invalid_token_data", key)

    def test_fernet_empty_data(self):
        """Fernet handles empty data."""
        key = derive_symmetric_key(b"pass", b"salt")
        token = fernet_encrypt(b"", key)
        recovered = fernet_decrypt(token, key)
        assert recovered == b""

    def test_fernet_large_data(self):
        """Fernet handles larger data."""
        key = derive_symmetric_key(b"pass", b"salt")
        plaintext = b"x" * 10000
        token = fernet_encrypt(plaintext, key)
        recovered = fernet_decrypt(token, key)
        assert recovered == plaintext


class TestRandomBytes:
    """Test random byte generation."""

    def test_generate_random_bytes_length(self):
        """Generated bytes have requested length."""
        for length in [8, 16, 24, 32]:
            data = generate_random_bytes(length)
            assert len(data) == length

    def test_generate_random_bytes_unique(self):
        """Multiple calls produce different results."""
        data1 = generate_random_bytes(16)
        data2 = generate_random_bytes(16)
        assert data1 != data2


class TestSessionKeys:
    """Test session key generation."""

    def test_session_key_aes128(self):
        """AES-128-CBC session key is 16 bytes."""
        key = generate_vault_session_key("aes-128-cbc")
        assert len(key) == 16

    def test_session_key_3des(self):
        """3DES session key is 24 bytes."""
        key = generate_vault_session_key("des-ede3-cbc")
        assert len(key) == 24

    def test_session_key_unknown_algo(self):
        """Unknown algorithm raises error."""
        with pytest.raises(VaultCryptoError, match="Unknown vault wrapping"):
            generate_vault_session_key("aes-256-gcm")

    def test_session_keys_unique(self):
        """Multiple calls produce different keys."""
        key1 = generate_vault_session_key("aes-128-cbc")
        key2 = generate_vault_session_key("aes-128-cbc")
        assert key1 != key2


class TestDataWrapping:
    """Test CBC data wrapping/unwrapping."""

    def test_wrap_unwrap_aes128(self):
        """AES-128-CBC wrap/unwrap roundtrip."""
        session_key = generate_vault_session_key("aes-128-cbc")
        data = b"vault data to encrypt"
        nonce, ciphertext = wrap_vault_data("aes-128-cbc", session_key, data)

        assert len(nonce) == 16  # AES IV is 16 bytes
        assert len(ciphertext) > len(data)  # Includes padding

        recovered = unwrap_vault_data("aes-128-cbc", session_key, nonce, ciphertext)
        assert recovered == data

    def test_wrap_unwrap_3des(self):
        """3DES wrap/unwrap roundtrip."""
        session_key = generate_vault_session_key("des-ede3-cbc")
        data = b"more vault data"
        nonce, ciphertext = wrap_vault_data("des-ede3-cbc", session_key, data)

        assert len(nonce) == 8  # 3DES IV is 8 bytes

        recovered = unwrap_vault_data("des-ede3-cbc", session_key, nonce, ciphertext)
        assert recovered == data

    def test_wrap_empty_data(self):
        """Wrapping empty data works."""
        session_key = generate_vault_session_key("aes-128-cbc")
        nonce, ciphertext = wrap_vault_data("aes-128-cbc", session_key, b"")

        # Even empty data gets padded
        assert len(ciphertext) > 0

        recovered = unwrap_vault_data("aes-128-cbc", session_key, nonce, ciphertext)
        assert recovered == b""

    def test_wrap_large_data(self):
        """Wrapping large data works."""
        session_key = generate_vault_session_key("aes-128-cbc")
        data = os.urandom(50000)
        nonce, ciphertext = wrap_vault_data("aes-128-cbc", session_key, data)
        recovered = unwrap_vault_data("aes-128-cbc", session_key, nonce, ciphertext)
        assert recovered == data

    def test_unwrap_wrong_key(self):
        """Unwrapping with wrong key fails."""
        key1 = generate_vault_session_key("aes-128-cbc")
        key2 = generate_vault_session_key("aes-128-cbc")
        nonce, ciphertext = wrap_vault_data("aes-128-cbc", key1, b"data")

        with pytest.raises(VaultCryptoError):
            unwrap_vault_data("aes-128-cbc", key2, nonce, ciphertext)

    def test_unwrap_wrong_nonce(self):
        """Unwrapping with wrong nonce produces garbage."""
        session_key = generate_vault_session_key("aes-128-cbc")
        nonce1, ciphertext = wrap_vault_data("aes-128-cbc", session_key, b"data")
        nonce2 = generate_random_bytes(16)

        # Wrong nonce produces invalid padding
        with pytest.raises(VaultCryptoError, match="padding"):
            unwrap_vault_data("aes-128-cbc", session_key, nonce2, ciphertext)

    def test_wrap_unknown_algorithm(self):
        """Unknown algorithm raises error."""
        session_key = generate_random_bytes(32)
        with pytest.raises(VaultCryptoError, match="Unknown vault wrapping"):
            wrap_vault_data("aes-256-gcm", session_key, b"data")

    def test_unwrap_unknown_algorithm(self):
        """Unknown algorithm raises error."""
        session_key = generate_random_bytes(32)
        nonce = generate_random_bytes(16)
        with pytest.raises(VaultCryptoError, match="Unknown vault wrapping"):
            unwrap_vault_data("aes-256-gcm", session_key, nonce, b"data")

    def test_wrap_nonce_is_random(self):
        """Each wrap generates unique nonce."""
        session_key = generate_vault_session_key("aes-128-cbc")
        nonce1, _ = wrap_vault_data("aes-128-cbc", session_key, b"data")
        nonce2, _ = wrap_vault_data("aes-128-cbc", session_key, b"data")
        assert nonce1 != nonce2
